config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  root to: 'homes#top'
  get 'top/index'
  get "about" => "top#about" , as: "about"
  get "answer" => "top#answer" , as: "answer"


# scope module: "customers" do

  resources :customers


  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'


  resources :categories, only: [:show]

  resources :kinds, only: [:show]

  resources :memos

  resources :chats do
    resources :comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end

  resources :discussions do
    resources :opinions, only: [:create, :show, :destroy]
     resource :bookmarks, only: [:create, :destroy]
  end

# end


 namespace :admins do

  resources :customers

  resources :chats do
    resources :comments, only: [:create, :destroy]
  end

  resources :discussions do
    resources :opinions, only: [:create, :destroy]
  end

 end

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/confirm', to: 'contacts#confirm'
  get 'done', to: 'contacts#done', as: 'done'






 end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :discussion
  validates :customer_id, uniqueness: { scope: :discussion_id }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :discussion_category_relations
  has_many :discussions, through: :discussion_category_relations
end

app/models/categorye.rb
class Categorye < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :kind_relations
  has_many :kinds, through: :kind_relations

  validates :title, presence: true
  validates :nickname, presence: true
  # validates :content, presence: true

  def self.search(keyword)
    where(["title like? OR introduction like? OR nickname like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer).exists?
  end

  def self.kind
    chat.where(kind_id: @kind )
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :chat
  belongs_to :customer
  
  validates :nickname, presence: true
  # validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord


  validates :nickname, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :opinions, dependent: :destroy

  def self.search(keyword)
     where(["email like?  OR nickname like?", "%#{keyword}%" , "%#{keyword}%"])
  end


end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :customer
  has_many :opinions, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  # has_many :hashtagposts, dependent: :destroy
  # has_many :hashtags, through: :hashtagposts
  has_many :discussion_category_relations
  has_many :categories, through: :discussion_category_relations

  validates :title, presence: true
  validates :nickname, presence: true

  # validates :introduction, presence: true


  def bookmarked_by?(customer)
    bookmarks.where(customer_id: customer).exists?
  end

  def self.search(keyword)
    where(["title like? OR introduction like? OR nickname like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  
  def self.category
    Discussion.where(category_id: @category )
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :chat
  validates :customer_id, uniqueness: { scope: :chat_id }
end

app/models/folder.rb
class Folder < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: {maximum:99}
  has_many :hashtag_post_images, dependent: :destroy
  has_many :discussions, through: :hashtagpost
end

app/models/hashtagpost.rb
class Hashtagpost < ApplicationRecord
  belongs_to :discussion
  belongs_to :Hashtag
  validates  :discussion_id, presence: true
  validates  :Hashtag_id,   presence: true
end


# 今後実装予定　ハッシュタグ

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  
  
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :kind_relations
  has_many :chats, through: :kind_relations
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/memo.rb
class Memo < ApplicationRecord
   belongs_to :customer

  def self.search(keyword)
    where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
  end

  validates :title, presence: true
  validates :body, presence: true



end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :discussion
  belongs_to :customer


  validates :nickname, presence: true
  # validates :content, presence: true
end

app/controllers/admins/chats_controller.rb
class Admins::ChatsController < ApplicationController
  before_action :authenticate_admin!

    def index
      @chats = Chat.all
      @chats = Chat.search(params[:keyword])
      @keyword = params[:keyword]
      render "index"
    end

    def destroy
      chat = Chat.find(params[:id])
      chat.destroy
      redirect_to admins_chats_path
    end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_customer!

    def index
      @chats = Chat.all.order('updated_at DESC')
      # @page = Article.all.page(params[:page])
      @kinds = Kind.all
      @chats = Chat.order('updated_at DESC').search(params[:keyword]).page(params[:page]).per(15)
      @keyword = params[:keyword]
      render "index"
    end
  
    def new
      @chat = Chat.new
      @chat = current_customer.chats.build
    end
  
    def create
      @chat = Chat.new(chat_params)
      @chat = current_customer.chats.build(chat_params)
      @chat.customer_id = current_customer.id
      @chat.save
      redirect_to chats_path
    end
  
    def show
     @chat = Chat.find(params[:id])
     @comment = Comment.new
     @comments= @chat.comments.order('updated_at DESC').page(params[:page]).per(10)
    end
  
    def edit
      @chat = Chat.find(params[:id])
    end
  
    def update
      @chat = Chat.find(params[:id])
      @chat.update(chat_params)
      redirect_to "/chats/#{@chat.id}"
    end
  
    def destroy
      @chat = Chat.find(params[:id])
      @chat.destroy
      redirect_to "/chats"
    end
  
    def search
      @chats = Chat.search(params[:keyword])
      @keyword = params[:keyword]
    　render "index"
    end
  
    def kind
      @kind = chat.find_by(kind_id: params[:kind_id])
      @Chats = chat.kind
    end
  
  
    private
  
    def chat_params
      params.require(:chat).permit(:title, :nickname, :customer_id, kind_ids: [])
    end

end

app/helpers/admins/chats_helper.rb
module Admins::ChatsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
  
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admins/chats/index.html.erb
<div class="management0">
  <%= form_with url: admins_chats_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword,  size: 40  %>
    <%= f.submit "検索" %>
  <% end %>
</div>

<h2>ChatRoomスレッド一覧</h2>
  <div class="management1">
    <table>
      <tr>
        <th>ニックネーム</th>
        <th>作成スレッド</th>
        <th>作成日時</th>
        <th>スレッド削除</th>
        <th></th>
      </tr>
      <% @chats.each do |chat| %>
        <tr>
          <td><%= chat.nickname %></td>
          <td><%= chat.title %></td>
          <td><%= chat.created_at.strftime("%Y/%m/%d %H:%M:%S ")  %></td>
          <td><%= link_to 'Delete', admins_chat_path(chat.id), method: :delete %></td>
      <% end %>
        </tr>
    </table>
  </div>

app/views/chats/_new.html.erb
<!--<%# chats.each do |chat| %>-->
<!--    <tr>-->
<!--        <td><%#= chat.customer.nickname %></td>-->
<!--        <td><%#= chat.title %></td>-->
<!--        <td><%#= chat.introduction %></td>-->
<!--        <td><%#= link_to "詳細", chat_path(chat) %></td>-->
<!--        <td><%#= link_to "編集", edit_chat_path(chat) %></td>-->
<!--        <td><%#= link_to "削除", chat_path(chat), method: :delete, remote: true %></td>-->
<!--    </tr>-->
<!--<%#end %>-->

<!--部分テンプレート　修正予定分-->

app/views/chats/edit.html.erb
  <div class="chat-1">
    <%= link_to "スレッド一覧に戻る", chats_path %>
  </div>

  <div class="chat-1-1">
    タイトルを編集する
  </div>

  <%= form_with model: @chat ,local: true do |f| %>
    <div class="chat-2">
      タイトル: <%= f.text_field :title %><br />
    </div>
    <div class="chat-3">
      作成者名: <%= f.text_field :nickname %><br />
    </div>
    <div class="chat-5-1">
      <%= f.submit "送信", class: "button"  %>
    </div>
  <% end %>

app/views/chats/index.html.erb
<div class="search" >
      <%= form_with url: chats_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword,  size: 40, :placeholder => "キーワードを入力してください"  %>
        <%= f.submit "検索" %>
      <% end %>
</div>

<div class="search1"><%= link_to "スレッドを作る", new_chat_path %></div>

<div class="outline">
  <div class="side">
    【カテゴリー】<br />
      &nbsp;カテゴリー追加のご要望は<%= link_to "こちら", new_contact_path  %>
      <div style="width:250px;height:650px;overflow:scroll;">
        <% @kinds.each do |kind| %><br />
          <%= kind.name %>
          <% chat_ids = KindRelation.where(kind: kind).map(&:chat_id) %>
            <% Chat.where(id: chat_ids).each do |chat| %><br />
              <%= link_to chat.title, chat_path(chat)  %>
            <% end %>
        <% end %>
      </div>
  </div>

  <div class="submain">
    <h1>ChatRoom</h1>
      <h5>「足音」って何？については<%= link_to "About", about_path %>をご覧ください。</h5>
      <h5>もっと詳しく教えてよ<%= link_to "Q&A", answer_path  %></h5>
    <hr>
    <h2>仲良くお話しましょう</h2>
      <% @chats.each do |chat| %>
        <%= link_to chat.title, chat_path(chat) %>&nbsp &nbsp &nbsp
        (<%= chat.comments.count %>)<br />
      <% end %>
    <div class ="paginate">
      <%= paginate @chats %>
    </div>
  </div>
</div>

app/views/chats/new.html.erb
<div class="chat-1">
  <%= link_to "スレッド一覧に戻る", chats_path %>
</div>

  <%= form_with model:[@chat], date: {remote: true} do |f| %>
    <div class="chat-2">
      【タイトル】<br /><%= f.text_field :title %><br />
    </div>
    <div class="chat-3">
      【作成者】<br /><%= f.text_field :nickname %><br />
    </div>
    <div class="chat-4">
      <%= f.label :kind, '【カテゴリ】' %>
    </div>
    <div class="chat-4-1">
      <%= f.collection_check_boxes(:kind_ids, Kind.all, :id, :name) do |kind| %>
        <%= kind.label do %>
          <%= kind.check_box %>
          <%= kind.text %>
        <% end %>
      <% end %>
    </div>
    <div class="chat-5-1">
      <%= f.submit "送信", class: "button" %>
    </div>
  <% end %>

app/views/chats/show.html.erb
<div class="chat-box">
  <div class="chat-item-1">
    <h1><%= @chat.title %></h1>
          スレッド開設日:<%= @chat.created_at.strftime("%Y/%m/%d ") %></br>
          スレッドオーナー:<%= @chat.customer.nickname %></br>
        <% @chat.kinds.each do |kind| %>
          カテゴリ:<%= kind.name %></br>
        <% end %>
        <% if customer_signed_in? && @chat.customer_id == current_customer.id %>
          <%= link_to "タイトルを編集する", edit_chat_path(@chat) %></br>
          <%= link_to "スレッドを削除する", chat_path(@chat), method: :delete, data: { confirm: "本当に削除しますか？" } %></br>
        <% end %>
        <%= link_to "スレッド一覧に戻る", chats_path %></br>
          <% if @chat.favorited_by?(current_customer) %>
            <%= link_to "ブックマークを外す", chat_favorites_path(@chat), method: :delete  %>
          <% else %>
            <%= link_to "ブックマーク", chat_favorites_path(@chat), method: :chat  %>
          <% end %>

        <%= form_for @comment, url: chat_comments_path(@chat, @comment), data: {remote: true} do |f| %>
          <div class="chat-item-2-1">
            ニックネーム:</br> <%= f.text_field :nickname %> <br>
          </div>
          <div class="chat-item-2-2">
            コメント:</br> <%= f.text_area :content, :size=>"33x10" %> <br>
            <%= f.submit "書き込む", class: "button"  %>
            <div class="api"></br>【注意】<%= link_to "内容よっては書き込みが行えません！", answer_path %>
            </div>
　        </div>
        <% end %>
    </div>

  <div class="chat-item-3">
     <% @comments.each_with_index do |comment, index| %>
       <%= index + 1 %>：
       <%= comment.nickname %>
       <%= comment.created_at.strftime("%Y/%m/%d %H:%M:%S ") %>
       <!--スコア<%#= comment.score %>-->
       <% if customer_signed_in? && comment.customer_id == current_customer.id %>
         <%= link_to "削除する", chat_comment_path(@chat, comment), method: :delete, remote: true  %>
       <% end %></br>
         <%#= simple_format(h(comment.content).html_safe) %>
       <%= sanitize(comment.content.gsub("\n", "<br>")) %>
       <hr>
     <% end %>
  </div>
</div>

<div class="chat-item-4">
  <%= paginate @comments %>
</div>