config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  root to: 'homes#top'
  get 'top/index'
  get "about" => "top#about" , as: "about"
  get "answer" => "top#answer" , as: "answer"


# scope module: "customers" do

  resources :customers


  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'


  resources :categories, only: [:show]

  resources :kinds, only: [:show]

  resources :memos

  resources :chats do
    resources :comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end

  resources :discussions do
    resources :opinions, only: [:create, :show, :destroy]
     resource :bookmarks, only: [:create, :destroy]
  end

# end


 namespace :admins do

  resources :customers

  resources :chats do
    resources :comments, only: [:create, :destroy]
  end

  resources :discussions do
    resources :opinions, only: [:create, :destroy]
  end

 end

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/confirm', to: 'contacts#confirm'
  get 'done', to: 'contacts#done', as: 'done'






 end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :customer
  has_many :opinions, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  # has_many :hashtagposts, dependent: :destroy
  # has_many :hashtags, through: :hashtagposts
  has_many :discussion_category_relations
  has_many :categories, through: :discussion_category_relations

  validates :title, presence: true
  validates :nickname, presence: true

  # validates :introduction, presence: true


  def bookmarked_by?(customer)
    bookmarks.where(customer_id: customer).exists?
  end

  def self.search(keyword)
    where(["title like? OR introduction like? OR nickname like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  
  def self.category
    Discussion.where(category_id: @category )
  end
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: {maximum:99}
  has_many :hashtag_post_images, dependent: :destroy
  has_many :discussions, through: :hashtagpost
end

app/controllers/admins/discussions_controller.rb
class Admins::DiscussionsController < ApplicationController
  before_action :authenticate_admin!

    def index
      @discussions = Discussion.all
      @discussions = Discussion.search(params[:keyword])
      @keyword = params[:keyword]
      render "index"
    end

    def destroy
      discussion = Discussion.find(params[:id])
      discussion.destroy
      redirect_to admins_discussions_path
    end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
   before_action :authenticate_customer!

     def index
      @discussions = Discussion.all
      @categories = Category.all
      @discussions = Discussion.order('updated_at DESC').search(params[:keyword]).page(params[:page]).per(15)
      @keyword = params[:keyword]
      render "index"
     end


    def new
      @discussion = Discussion.new
      @discussion = current_customer.discussions.build
    end

    def create
      @discussion = Discussion.new(discussion_params)
      @discussion.customer_id = current_customer.id
      @discussion.save
      redirect_to discussions_path
    end

    def show
     @discussion = Discussion.find(params[:id])
     @opinion = Opinion.new
     @opinions= @discussion.opinions.order('updated_at DESC').page(params[:page]).per(8)
    end

    def edit
      @discussion = Discussion.find(params[:id])
    end

    def update
      @discussion = Discussion.find(params[:id])
      @discussion.update(discussion_params)
      redirect_to "/discussions/#{@discussion.id}"
    end


    def destroy
      @discussion = Discussion.find(params[:id])
      @discussion.destroy
      redirect_to "/discussions"
    end

    def search
      @discussions = Discussion.search(params[:keyword])
      @keyword = params[:keyword]
      render "index"
    end


    def category
      @category = discussion.find_by(category_id: params[:category_id])
      @Discussions = discussion.category
    end

    private

    def discussion_params
      params.require(:discussion).permit(:title, :nickname, :customer_id,  category_ids: [])
    end

end

app/helpers/admins/discussions_helper.rb
module Admins::DiscussionsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def render_with_hashtags(introduction)
    introduction.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { |word| link_to word, "/discussion/hashtag/#{word.delete("#")}",data: {"turbolinks" => false} }.html_safe
  end
end



#   def render_with_hashtags(tag_name, tag_id)
#     tag_name.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/discussion/hashtag/#{word.delete("#")}?tag_id=#{tag_id}"}.html_safe
#   end

app/views/discussions/edit.html.erb
 <div class="discussion-1">
   <%= link_to "スレッド一覧に戻る", discussions_path %>
 </div>
   <div class="discussion-1-1">
     タイトルを編集する
   </div>
     <%= form_with model: @discussion ,local: true do |f| %>
       <div class="discussion-2">
         タイトル: <%= f.text_field :title %> <br />
       </div>
       <div class="discussion-3">
         作成者名: <%= f.text_field :nickname %> <br />
       </div>
       <div class="discussion-5-1">
         <%= f.submit "送信", class: "button" %>
       </div>
    <% end %>

app/views/discussions/hashtag.html.erb
<!--ハッシュタグ実装予定-->

<!-- <div class= "hashtag-name">-->
<!--    <%# @hashtags.sort.reverse.each do |count| %>-->
<!--        <%# count[1].each do |hashtag| %>-->
<!--            <p><%#= link_to  "(#{hashtag.hashname}) (#{hashtag.discussions.count}) 件","/discussion/hashtag/#{hashtag.hashname}",data: {"turbolinks" => false} %>-->
<!--            </p>-->
<!--        <%# end %>-->
<!--    <%# end %>-->
<!--</div>s-->

app/views/discussions/index.html.erb
<div class="search">
   <%= form_with url: discussions_path, method: :get, local: true do |f| %>
     <%= f.text_field :keyword, value: @keyword,  size: 40, :placeholder => "キーワードを入力してください"  %>
     <%= f.submit "検索" %>
   <% end %>
</div>

<div class="search1"><%= link_to "スレッドを作る", new_discussion_path %></div>

<div class="outline">
  <div class="side">
    【カテゴリー】<br />
      &nbsp;カテゴリー追加のご要望は<%= link_to "こちら", new_contact_path  %>
        <div style="width:250px;height:650px;overflow:scroll;">
          <% @categories.each do |category| %><br />
            <%= category.name %>
            <% discussion_ids = DiscussionCategoryRelation.where(category: category).map(&:discussion_id) %>
              <% Discussion.where(id: discussion_ids).each do |discussion| %><br />
                <%= link_to discussion.title, discussion_path(discussion)  %>
              <% end %>
          <% end %>
      </div>
     </div>

  <div class="submain">
    <h1>DiscussionRoom</h1>
      <h5>「足音」って何？については<%= link_to "About", about_path %>をご覧ください。</h5>
      <h5>もっと詳しく教えてよ<%= link_to "Q&A", answer_path  %></h5>
    <hr>
    <h2>生産的なお話をしましょう</h2>
      <% @discussions.each do |discussion| %>
        <%= link_to discussion.title, discussion_path(discussion) %> &nbsp &nbsp &nbsp
        (<%= discussion.opinions.count %>)<br />
        <!--<%#= current_customer.discussions.where('created_at > ?', Date.today).count %>-->
      <% end %>
    <div class ="paginate">
      <%= paginate @discussions %>
    </div>
   </div>
</div>

app/views/discussions/new.html.erb
	<div class="discussion-1">
	  <%= link_to "スレッド一覧に戻る", discussions_path %>
	</div>

	<%= form_with model:[@discussion], date: {remote: true} do |f| %>
	  <div class="discussion-2">
	    【タイトル】<br /><%= f.text_field :title %> <br />
	  </div>
	  <div class="discussion-3">
	    【作成者】<br /><%= f.text_field :nickname %> <br />
	  </div>
	  <div class="discussion-4">
	    <%= f.label :category, '【カテゴリ】' %>
	  </div>
	  <div class="discussion-4-1">
	    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
		    <%= category.label do %>
		      <%= category.check_box %>
		      <%= category.text %>
		    <% end %>
		  <% end %>
		</div>
	  <div class="discussion-5-1">
	    <%= f.submit "送信", class: "button" %>
	  </div>
	<% end %>

app/views/discussions/show.html.erb
<div class="discussion-box">
  <div class="discussion-item-1">
    <h1><%= @discussion.title %></h1>
            スレッド開設日:<%= @discussion.created_at.strftime("%Y/%m/%d ") %><br />
            スレッドオーナー:<%= @discussion.customer.nickname %><br />
          <% @discussion.categories.each do |category| %>
            カテゴリ:<%= category.name %><br />
          <% end %>
            <% if customer_signed_in? && @discussion.customer_id == current_customer.id %>
              <%= link_to "タイトルを編集する", edit_discussion_path(@discussion) %><br />
              <%= link_to "スレッドを削除する", discussion_path(@discussion), method: :delete, data: { confirm: "本当に削除しますか？" } %><br />
            <% end %>
          <%= link_to "スレッド一覧に戻る", discussions_path %><br />
            <% if @discussion.bookmarked_by?(current_customer) %>
              <%= link_to "ブックマークを外す", discussion_bookmarks_path(@discussion), method: :delete %>
            <% else %>
              <%= link_to "ブックマーク", discussion_bookmarks_path(@discussion), method: :discussion %>
            <% end %>

        <%= form_for @opinion, url: discussion_opinions_path(@discussion, @opinion), data: {remote: true} do |f| %>
          <div class="discussion-item-2-1">
            ニックネーム:</br> <%= f.text_field :nickname %><br />
          </div>
          <div class="discussion-item-2-2">
            コメント:</br> <%= f.text_area :content, :size=>"33x10" %><br />
            <!--<%#= text_url_to_link(h(opinion.url)).html_safe %>-->
            <%= f.submit "書き込む", class: "button"  %>
            <div class="api"></br>【注意】<%= link_to "内容よっては書き込みが行えません！", answer_path %>
            </div>
          </div>
        <% end %>
  </div>

  <div class="discussion-item-3">
     <% @opinions.each_with_index do |opinion, index| %>
       <%= index + 1 %>：
       <%= opinion.nickname %>
       <%= opinion.created_at.strftime("%Y/%m/%d %H:%M:%S ") %>
       <!--スコア<%#= comment.score %>-->
       <% if customer_signed_in? && opinion.customer_id == current_customer.id %>
         <%= link_to "削除する", discussion_opinion_path(@discussion, opinion), method: :delete, remote: true  %>
       <% end %><br />
         <%#= simple_format(h(comment.content).html_safe) %>
       <%= sanitize(opinion.content.gsub("\n", "<br>")) %>
       <hr>
     <% end %>
  </div>
</div>

<div class="discussion-item-4">
  <%= paginate @opinions %>
</div>