config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  root to: 'homes#top'
  get 'top/index'
  get "about" => "top#about" , as: "about"
  get "answer" => "top#answer" , as: "answer"


# scope module: "customers" do

  resources :customers


  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'


  resources :categories, only: [:show]

  resources :kinds, only: [:show]

  resources :memos

  resources :chats do
    resources :comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end

  resources :discussions do
    resources :opinions, only: [:create, :show, :destroy]
     resource :bookmarks, only: [:create, :destroy]
  end

# end


 namespace :admins do

  resources :customers

  resources :chats do
    resources :comments, only: [:create, :destroy]
  end

  resources :discussions do
    resources :opinions, only: [:create, :destroy]
  end

 end

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/confirm', to: 'contacts#confirm'
  get 'done', to: 'contacts#done', as: 'done'






 end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :opinions, dependent: :destroy

  def self.search(keyword)
     where(["email like?  OR nickname like?", "%#{keyword}%" , "%#{keyword}%"])
  end


end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!

    def index
      @customers = Customer.all
      @customers = Customer.search(params[:keyword])
      @keyword = params[:keyword]
      render "index"
    end

    def destroy
      customer = Customer.find(params[:id])
      customer.destroy
      redirect_to admins_customers_path
    end


end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
   before_action :authenticate_customer!

  def index

  end

  def show
      @nickname = current_customer.nickname
      @chats = current_customer.chats
      @discussions = current_customer.discussions
      #byebug
      @threads = Chat.where(id: Comment.where(customer_id: current_customer.id).pluck(:chat_id))
      @texts = Discussion.where(id: Opinion.where(customer_id: current_customer.id).pluck(:discussion_id))
      @bookmarks = Bookmark.where(customer_id: current_customer.id)
      @favorites = Favorite.where(customer_id: current_customer.id)
  end

  def edit
      @customer = Customer.find(params[:id])
  end

  def update
      @customer = Customer.find(params[:id])
       if current_customer== @customer
       else
        redirect_to root_url
       end
  end

  def withdrawal
      @customer = Customer.find(params[:id])
      @customer.update(is_deleted: true)
      reset_session
      flash[:notice] = "退会処理を実行いたしました"
      redirect_to root_path
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/show.html.erb
<div class="mypage5">
  ニックネーム：<%= @nickname %></br>
  ※<%= link_to '登録情報を変更する', edit_customer_registration_path %>
  ※<%= link_to '退会する', unsubscribe_path(current_customer) %>
</div>

<h2>マイページ</h2>
  <div class="boxcontainer">
    <div class="tab">
      <input type="radio" name="tab" id="meat1" checked>
        <label for="meat1"><%= @nickname %>の参加スレッド</label>
        <input type="radio" name="tab" id="meat2">
        <label for="meat2"><%= @nickname %>のBookmark一覧</label>
          <div class="foods">
            <ul>
              <li>
                <div class="box-b">ChatRoom(直近5件の投稿を表示)</div>
                </br>
                  <% @threads.each do |thread| %>
                    <%= link_to thread.title, chat_path(thread) %><br />
                        《最新コメント》<br />
                        <% thread.comments.order(created_at: "DESC").limit(5).each do |comment|  %>
                        <%= comment.nickname %>&nbsp&nbsp
                        <%= comment.content %><br />
                        <% end %>
                        <br />
                    <% end %>
              </li>
              <li>
                <div class="box-b">DiscussionRoom(直近5件の投稿を表示)</div>
                <br />
                  <% @texts.each do |text| %>
                    <%= link_to text.title, discussion_path(text) %><br />
                      《最新コメント》<br />
                      <% text.opinions.order(created_at: "DESC").limit(5).each do |opinion|  %>
                      <%= opinion.nickname %>&nbsp&nbsp
                      <%= opinion.content %><br />
                      <% end %>
                      </br>
                  <% end %>
                </li>
            </ul>
            <ul>
              <li>
                <div class="box-b"> ChatRoom</div>
                  <% @favorites.each do |favorite| %><br />
                    <%= favorite.chat.customer.nickname %>:
                    <%= link_to chat_path(favorite.chat) do %>
                    <%= favorite.chat.title %>
                    <% end %>
                    </br>
                 <% end %>
                 <br />
              </li>
              <li>
                <div class="box-b">DiscussionRoom</div>
                  <% @bookmarks.each do |bookmark| %><br />
                    <%= bookmark.discussion.customer.nickname %>:
                    <%= link_to discussion_path(bookmark.discussion) do %>
                      <%= bookmark.discussion.title %>
                    <% end %>
                    <br />
                  <% end %>
              </li>
            </ul>
        </div>
      </div>
   </div>

app/views/customers/unsubscribe.html.erb
<div class="subscribe1">
  <h2>退会お手続き</h2>
    退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br />
    再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br />
    本当に退会してよろしいですか？</br>
      <%= link_to "退会する", withdrawal_path, method: :patch, data: { confilm: "本当に退会しますか？" } %>
      <%= link_to "退会しない", customer_path(current_customer) %>
</div>