config/routes.rb
Rails.application.routes.draw do


devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  root to: 'homes#top'
  get 'top/index'
  get "about" => "top#about" , as: "about"
  get "answer" => "top#answer" , as: "answer"


# scope module: "customers" do

  resources :customers


  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'


  resources :categories, only: [:show]

  resources :kinds, only: [:show]

  resources :memos

  resources :chats do
    resources :comments, only: [:create, :destroy]
     resource :favorites, only: [:create, :destroy]
  end

  resources :discussions do
    resources :opinions, only: [:create, :show, :destroy]
     resource :bookmarks, only: [:create, :destroy]
  end

# end


 namespace :admins do

  resources :customers

  resources :chats do
    resources :comments, only: [:create, :destroy]
  end

  resources :discussions do
    resources :opinions, only: [:create, :destroy]
  end

 end

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'contacts/confirm', to: 'contacts#confirm'
  get 'done', to: 'contacts#done', as: 'done'






 end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :discussion
  validates :customer_id, uniqueness: { scope: :discussion_id }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :discussion_category_relations
  has_many :discussions, through: :discussion_category_relations
end

app/models/categorye.rb
class Categorye < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :kind_relations
  has_many :kinds, through: :kind_relations

  validates :title, presence: true
  validates :nickname, presence: true
  # validates :content, presence: true

  def self.search(keyword)
    where(["title like? OR introduction like? OR nickname like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer).exists?
  end

  def self.kind
    chat.where(kind_id: @kind )
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :chat
  belongs_to :customer
  
  validates :nickname, presence: true
  # validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord


  validates :nickname, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :opinions, dependent: :destroy

  def self.search(keyword)
     where(["email like?  OR nickname like?", "%#{keyword}%" , "%#{keyword}%"])
  end


end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :customer
  has_many :opinions, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  # has_many :hashtagposts, dependent: :destroy
  # has_many :hashtags, through: :hashtagposts
  has_many :discussion_category_relations
  has_many :categories, through: :discussion_category_relations

  validates :title, presence: true
  validates :nickname, presence: true

  # validates :introduction, presence: true


  def bookmarked_by?(customer)
    bookmarks.where(customer_id: customer).exists?
  end

  def self.search(keyword)
    where(["title like? OR introduction like? OR nickname like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  
  def self.category
    Discussion.where(category_id: @category )
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :chat
  validates :customer_id, uniqueness: { scope: :chat_id }
end

app/models/folder.rb
class Folder < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: {maximum:99}
  has_many :hashtag_post_images, dependent: :destroy
  has_many :discussions, through: :hashtagpost
end

app/models/hashtagpost.rb
class Hashtagpost < ApplicationRecord
  belongs_to :discussion
  belongs_to :Hashtag
  validates  :discussion_id, presence: true
  validates  :Hashtag_id,   presence: true
end


# 今後実装予定　ハッシュタグ

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  
  
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :kind_relations
  has_many :chats, through: :kind_relations
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/memo.rb
class Memo < ApplicationRecord
   belongs_to :customer

  def self.search(keyword)
    where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
  end

  validates :title, presence: true
  validates :body, presence: true



end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :discussion
  belongs_to :customer


  validates :nickname, presence: true
  # validates :content, presence: true
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れの方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="heading">
     <a href="/">〜足音【ASHIOTO】〜</a>
  </div>
  <nav>
    <ul class="nav-list">
      <% if customer_signed_in? %>
             <li class="nav-list-item"> <%= link_to "■ChatRoom", chats_path %></li>
             <li class="nav-list-item"><%= link_to "■DiscussionRoom", discussions_path %></li>
             <li class="nav-list-item"> <%= link_to "■MemoRoom", new_memo_path %></li>
             <li class="nav-list-item"><%= link_to "■Mypage", "/customers/#{current_customer.id}" %></li>
             <li class="nav-list-item"><%= link_to "■About", about_path %></li>
             <li class="nav-list-item"><%= link_to "■Q&A", answer_path  %> </li>
             <li class="nav-list-item"><%= link_to "■Contact", new_contact_path  %></li>
             <li class="nav-list-item"><%= link_to "■Logout", destroy_customer_session_path, method: :delete  %></li>
             <li class="nav-list-item" class="SNS"><a href="https://www.instagram.com/ashioto_0904/"><span class="fa fa-instagram"></span></a></li>
      <% elsif admin_signed_in? %>
             <li class="nav-list-item"><%= link_to ' Customer', admins_customers_path %></li>
             <li class="nav-list-item"><%= link_to ' ChatRoom', admins_chats_path %></li>
             <li class="nav-list-item"><%= link_to ' DiscussionRoom', admins_discussions_path  %></li>
             <li class="nav-list-item"><%= link_to ' Logout', destroy_admin_session_path, method: :delete  %></li>
         </div>
      <% else %>
             <li class="nav-list-item"><%= link_to "■会員登録", new_customer_registration_path %> </li>
             <li class="nav-list-item"> <%= link_to "■ログイン", new_customer_session_path %> </li>
             <li class="nav-list-item"><%= link_to "■About", about_path  %></li>
             <li class="nav-list-item"><%= link_to "■F&Q", answer_path  %></li>
             <li class="nav-list-item" class="SNS"><a href="https://www.instagram.com/ashioto_0904/">■<span class="fa fa-instagram"></span></a></li>
         </div>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_search.html.erb
 <div class="search-form">
  <%= form_with url: chats_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword,  size: 40  %>
    <%= f.submit "検索" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Ashioto</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width,initial-scale=1,0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script src="https://use.fontawesome.com/926fe18a63.js">

        </script>
        <script>
        $("html").css("zoom", $(window).width() / 1625);
        $(window).bind({
        "resize load orientationchange" : function(event) {
        var zoom = $(window).width() / 1625;
        $("html").css("zoom", zoom);
            }
        });
        </script>

    </head>

    <body>
      <%= render 'layouts/header' %>
        <main>
          <%= yield %>
        </main>
    </body>
</html>